### ISSUE TITLE
Custom functions give errors

### ISSUE THREAD

**Issue by rapodaca** [vtst/ow#7] opened 2012-03-06 00:25 UTC
I've been using the Soy Eclipse plugin and find it very well done. There's just one issue (more like a feature request):

After defining a custom function called "input", the plugin views it as an error. For example, this line:

{input('arg1', 'arg2) |noAutoescape}

is flagged with the error: "couldn't resolve reference to FunctionDeclaration 'input'".

Is there any way to either selectively ignore this error, or notify the Soy plugin of my custom function?

Thanks in advance.

**Comment by vtst** [comment] 2012-03-06 19:53
Hello!
Thanks for your feedback about the plugin.

I've the impression that your issue is the same as https://github.com/vtst/ow/issues/2.

In fact there are two different problems:
1. You need to declare your function by inserting a special comment like
// @function input 2 0
just after the {namespace ...} in your file. This was not documented, but I just added a few lines about that on the web page.
1. Because of a bug in the current version, {input('arg1', 'arg2')} will still not be correctly parsed. You need to write
   {print input('arg1', 'arg2')}
   This will be fixed in the next version, to be released by the end of the week.

Let me know if this addresses your problem!
Best

-- Vincent

**Comment by rapodaca** [comment] 2012-03-06 21:39
@vtst, many thanks - it works! Here's my template:

{namespace test}

// @function input 3

/**
- 
  */
  {template .foo}
  {print input('foo', 'bar', 'baz') |noAutoescape}
  {/template}

No errors and the template works just like it did before.

I actually like the way you've done this because it forces you to declare your functions in documentation, which is consistent with the Soy way (I think).

Thanks again.

**Comment by vtst** [comment] 2012-03-07 18:04
Thanks for your feedback, glad to see the problem is solved! I hence close the bug.

**Closed as completed by vtst** 2012-03-07 18:04 UTC
