### ISSUE TITLE
JS: NullPointerException during completion attempt

### ISSUE THREAD

**Issue by lnagy** [vtst/ow#31] opened 2012-05-04 21:07 UTC
When I hit CTRL+SPACE right after a dot, I get an exception. For example:

goog.events. + CTRL+SPACE

Platform Details:

Ow JavaScript
Version: 0.2.1

Darwin unison.local 11.3.0 Darwin Kernel Version 11.3.0: Thu Jan 12 18:47:41 PST 2012; root:xnu-1699.24.23~1/RELEASE_X86_64 x86_64

Eclipse IDE for JavaScript Web Developers.

Version: Indigo Service Release 2
Build id: 20120216-1857

Eclipse Platform

Version: 3.7.2.v20120207-1839-9gF7UHPDFxGjd-PqDr2jX_4yKaumkoHTz04_q-q
Build id: M20120208-0800

Eclipse XML Editors and Tools

Version: 3.3.2.v201112072049-7H7EFZ7DxumTmce4khcSkIiqoD8eDMKlT8Oz011P
Build id: 20120210195245

Exception:

!MESSAGE The 'Closure Completion Proposal Computer' proposal computer from the 'net.vtst.ow.eclipse.js.closure' plug-in did not complete normally. The extension has thrown a runtime exception.
!STACK 0
java.lang.NullPointerException
    at net.vtst.ow.closure.compiler.compile.CompilerRun.getTypeOfName(CompilerRun.java:268)
    at net.vtst.ow.closure.compiler.compile.CompilerRun.getTypeOfQualifiedName(CompilerRun.java:282)
    at net.vtst.ow.eclipse.js.closure.editor.contentassist.ClosureCompletionProposalCollector.getProposals(ClosureCompletionProposalCollector.java:49)
    at net.vtst.ow.eclipse.js.closure.editor.contentassist.ClosureCompletionProposalComputer.computeCompletionProposals(ClosureCompletionProposalComputer.java:32)
    at org.eclipse.wst.jsdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:298)
    at org.eclipse.wst.jsdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:258)
    at org.eclipse.wst.jsdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:244)
    at org.eclipse.wst.jsdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:213)
    at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1830)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:556)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:553)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:488)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
    at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:377)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3938)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3615)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:123)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)

**Comment by vtst** [comment] 2012-05-05 08:03
Hello,

Thanks a lot for the bug report.

I just pushed a fix in the code base in order to avoid the NullPointerException. However, my fear is that you will no longer get the NullPointerException, but will have no completion proposal. If this is the case, in order to investigate more, I'd need some more context information:
1. Does this happen whenever you try to get a completion proposal, or only in some cases?
2. Does this happen when you have a very simple JavaScript file (e.g. only goog.require('goog.events'); and then you try to get a completion proposal)?

Best,

-- Vincent

**Comment by lnagy** [comment] 2012-05-05 17:33
Hi,

Thanks for the quick reply :) By the way, how come that F3 (jump to
declaration) only works in some cases, but not all cases? For example, I
define an alias like "var E = goog.events.EventType;" and then when the
cursor is pointing at the variable "E", Eclipse refuses to jump to the
declaration. (It says something like "not a valid JavaScript text
selection".) On the other hand, ALT+<COMMA> works: it cycles through the
references to "E", which indicates to me that it parses the thing
correctly. Finally, code completion doesn't work on "E" as defined above.
Even if I use the "@type" annotation.

Anyway, comments inline.

On Sat, May 5, 2012 at 4:03 AM, vtst <
reply@reply.github.com

> wrote:
> 
> Hello,
> 
> Thanks a lot for the bug report.
> 
> I just pushed a fix in the code base in order to avoid the
> NullPointerException. However, my fear is that you will no longer get the
> NullPointerException, but will have no completion proposal. If this is the
> case, in order to investigate more, I'd need some more context information:
> 1. Does this happen whenever you try to get a completion proposal, or only
> in some cases?

No, only when there's no prefix yet. That is, if I type even a single
letter after "goog.events.", it works.

**Comment by vtst** [comment] 2012-05-05 18:02
Hi,

> By the way, how come that F3 (jump to declaration) only works in some cases, but not all cases?

I did not (yet) implement "jump to declaration" (though it should be quite easy to do). So you should have the same behavior as in legacy JSDT. It works in some time, but not all, because it does not perform a complete analysis of the source code as the Closure compiler would do.

> No, only when there's no prefix yet. That is, if I type even a single letter after "goog.events.", it works.

This is really weird.

> Maybe. I'm inside a goog.scope() function though. I'm not sure if that matters.

I does not seem to be a sufficient reason. I tried an example as simple as:

goog.require('goog.events');

goog.scope(function(foo) {
    var x = goog.events.
});

on my computer, and the completion proposal just after the dot works perfectly.

Could you please send me a minimal example in which you obsvere the problem (i.e. new project with only one file, and no external dependency other than the normal closure library)? I'll try to reproduce it on my computer?

**Comment by lnagy** [comment] 2012-05-05 20:41
OK, I'll try to come up with a minimal example. In the meanwhile, should I
open a feature request for "jump to declaration"? That's like the most
important feature of Eclipse that I depend on :)

On Sat, May 5, 2012 at 2:02 PM, vtst <
reply@reply.github.com

**Comment by vtst** [comment] 2012-05-05 20:59
Yes, please feel free to open the feature request, this will be a good reminder for me! I'll try to do it shortly.

**Closed as completed** 2012-09-22 11:08 UTC
