### ISSUE TITLE
Soy: Couldn't resolve reference to RegularTemplate

### ISSUE THREAD

**Issue by adamyork** [vtst/ow#43] opened 2012-05-15 20:55 UTC
Hi ! I apologize if this has been covered in an existing ticket , however I couldn't find it. I am receiving the error

> Couldn't resolve reference to RegularTemplate

This is happening when we have two .soy files declared under the same namespace , that reference one or more of eachother's templates. For example,
### SOY_FILE_A.soy

``` xml
{namespace foo}
/*
*
*/
{template .templateA}
{/template}
```
### SOY_FILE_B.soy

``` xml
{namespace foo}
/*
*
*/
{template .templateB}
{call .templateA/}{/call}
{/template}
```

In some other cases we use the fully qualified namespace of an external template, For example :
### SOY_FILE_C.soy

``` xml
{namespace foo}
/*
*
*/
{template .templateA}
{/template}
```
### SOY_FILE_D.soy

``` xml
{namespace bar}
/*
*
*/
{template .templateB}
{call foo.templateA/}{/call}
{/template}
```

Any feedback is greatly appreciated. Thanks again !

**Comment by vtst** [comment] 2012-05-16 15:52
Thanks for the bug report. I see what the problem is, I'll try to fix it shortly.

**Comment by vtst** [comment] 2012-05-16 16:42
This is fixed in the code base, and will be available in the next release.

**Closed as completed by vtst** 2012-05-16 16:42 UTC
